Course: Application of Accelerators WS 20/21  
Date: 27.09.2020   
Name, Matriculation Number: Ines Maltusch, 314539     

<br /> 

### **Exercise 1** 

**Task 3**

Function, which adds 2+2 :

In [44]:
def addition(parameter):          # function, named 'addition' with argument 'parameter'
    result = 2+2                  # calculation, that 'addition' performs
    return result                 # returns the result
    
print(addition(x))                # calling the function 'addition' and display of the result

4


Function, which multiples two 3x3 matrices:

In [46]:
import numpy as np                             # import of module numpy

def matrix_multiplication(m1, m2):             # function, named 'matrix_multiplication' with arguments 'm1' & 'm2' 
    m1 = np.array(a)                           # m1 defined as an array of a
    m2 = np.array(b)                           # m2 defined as an array of b
    result = np.dot(m1, m2)                    # performing the matrix multiplication of m1 and m2
    return result                              # returns the result

a = [1, 2, 3], [4, 5, 6], [7, 8, 9]            # definition of a
b = [1, 2, 3], [4, 5, 6], [7, 8, 9]            # definition of b

print(matrix_multiplication(a, b))             # calling the function 'matrix_multiplication' and display of the result

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
